"""create buckets

Revision ID: 9969bdeeb8ee
Revises: 
Create Date: 2026-04-27 10:41:02.069856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9969bdeeb8ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bandwidth_bytes', sa.Integer(), nullable=False),
    sa.Column('current_storage_bytes', sa.Integer(), nullable=False),
    sa.Column('ingress_bytes', sa.Integer(), nullable=False),
    sa.Column('egress_bytes', sa.Integer(), nullable=False),
    sa.Column('internal_transfer_bytes', sa.Integer(), nullable=False),
    sa.Column('count_write_requests', sa.Integer(), nullable=False),
    sa.Column('count_read_requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buckets_name'), 'buckets', ['name'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_bucket_id'), 'files', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_bucket_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_buckets_name'), table_name='buckets')
    op.drop_table('buckets')
    # ### end Alembic commands ###
