"""add bandwidth bytes to buckets

Revision ID: aad6233295ff
Revises: 5bdfb4170537
Create Date: 2026-04-19 16:04:31.732428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad6233295ff'
down_revision: Union[str, Sequence[str], None] = '5bdfb4170537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_buckets_name'), 'buckets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buckets_name'), table_name='buckets')
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###
